version: 1.0.{build}
environment:
install:
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#development'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false